Tweet_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('tweetapp.urls')),
    path("",include('django.contrib.auth.urls')),
    
]

tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('',views.listTweet,name ="İndex"),
    path('listtweet/', views.listTweet,name='ListTweet'),
    path('addtweet/', views.addTweet,name='AddTweet'),
    path('addtweetform/', views.addTweetForm,name='AddTweetForm'),
    path('addtweetmodelform/', views.addTweetModelForm,name='AddTweetModelForm'),
    path('signup/',views.SignUpView.as_view(),name="SignUp"),
    path('deletetweet/<int:id>',views.deletetweet,name="deletetweet"),
]

tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Tweet(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=255)


    def __str__(self):
        return f"Username: {self.username}, Tweet: {self.message}"

tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet


class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_input = forms.CharField(label="Message",max_length=255)


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["username","message"]

tweetapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse,reverse_lazy
from tweetapp.forms import AddTweetForm,AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


def listTweet(request):
    all_tweets = models.Tweet.objects.all()
    tweetdic= {"tweets": all_tweets}
    return render(request,'tweetapp/listtweet.html',context=tweetdic)

@login_required(login_url="/login") # Tweet eklemek için kullanıcı giriş yapmak zorunda, giriş yapmamış ise login sayfasına yönlendirilir.
def addTweet(request):
    if request.POST:
        message = request.POST["message"]
        models.Tweet.objects.create(username=request.user,message=message)
        return redirect(reverse('tweetapp:ListTweet'))
    return render(request,'tweetapp/addtweet.html')

def addTweetForm(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse('tweetapp:ListTweet'))
    else: 
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetform.html',context={"Form":form})
    
def addTweetModelForm(request):
    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse('tweetapp:ListTweet'))
    else: 
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetmodelform.html',context={"Form":form})
@login_required    
def deletetweet(request,id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect("tweetapp:ListTweet")




class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login") #Sadece gerekli olduğu zaman reverse çalışsın diye reverse_lazy 
    template_name = "registration/signup.html"

templates/base.html
{% load  static  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tweet App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Tweet Application</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "tweetapp:ListTweet" %}">List Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url "tweetapp:AddTweet" %}">Add Tweet</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link active" href="{% url "tweetapp:AddTweetForm" %}">Add Tweet Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url "tweetapp:AddTweetModelForm" %}">Add Tweet Model Form</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
              -->
              <li class="nav-item">
                <a class="nav-link active" href="{% url "login" %}">Login</a>
              </li>
              <li class="nav-item">
                <form action="{% url 'logout' %}?next=/" method="post">
                  {% csrf_token %}
                  <button type="submit" class="nav-link active btn btn-link">Logout</button>
                </form>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url "tweetapp:SignUp" %}">Sign Up</a>
              </li>
            </form>
          </div>
        </div>
      </nav>





    {% block content %}
    
    
    
    
    





    {% endblock  %}






</body>
</html>

tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="container"> 
      <!--
      <div class="mb-3">
        <label for="nickname" class="form-label">Nickname</label>
        <input class="form-control" id="nickname" name="nickname">
      </div>
      -->
      <div class="mb-3">
        <label for="message" class="form-label">Tweet</label>
        <input type="text" class="form-control" id="message" name="message">
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">Share Tweet</button>
  </div>
  </form>
{% endblock  %}

tweetapp/templates/tweetapp/addtweetform.html
{% extends "base.html" %}

{% block content %}
<h1> Add Tweet Form </h1>
<form action="" method="POST">
    {% csrf_token %}
    {{Form}}
    <button type="submit" class="btn btn-primary">Share Tweet</button>
  </form>
{% endblock  %}

tweetapp/templates/tweetapp/addtweetmodelform.html
{% extends "base.html" %}
{% load  static  %}
{% block content %}
<h1> Add Tweet Model Form </h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}
        
        {% for field in Form  %}
        <div class="mb-3">
            {{field.label_tag}}
            {{field}}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Share Tweet</button>
    </form>
</div>
{% endblock  %}

tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{% block content  %}
    <div class="container">
    {% for tweet in tweets  %}
        <div class="card" style="padding:10px">
            <div class="card-header" style="background-color: cornflowerblue;">
                <h4><b>{{tweet.username}}</b></h4>
            </div>
            <div class="card-body">
                <p class="card-text">{{tweet.message}}</p>
              </div>
              {% if tweet.username == user %}
              <a href="{% url "tweetapp:deletetweet" id=tweet.id %}" class = "btn btn-danger"> Delete </a>
              {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock  %}